=== Arrekusu/datamover/components/datamover-core/src/main/java/com/arekusu/datamover/model/jaxb/Model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.arekusu.com"
           xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.arekusu.com">
    <xs:element name="LinksType">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="EntityType" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="DefinitionType">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="EntityType"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="rootElement"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="FieldType">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="alias" use="optional"/>
                    <xs:attribute type="xs:string" name="column" use="optional"/>
                    <xs:attribute type="xs:string" name="order" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="ModelType">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="DefinitionType"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="version"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="EntityType">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="FieldsType" minOccurs="0"/>
                <xs:element ref="ReferencesType" minOccurs="0"/>
                <xs:element ref="LinksType" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="alias" use="optional"/>
            <xs:attribute type="xs:string" name="sourceField" use="optional"/>
            <xs:attribute type="xs:string" name="destinationField" use="optional"/>
            <xs:attribute type="xs:string" name="destinationFieldOrder" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="FieldsType">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="FieldType" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="schema"/>
            <xs:attribute type="xs:string" name="table"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ReferencesType">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="EntityType" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Arrekusu/datamover/src/main/resources/Model.xml
<?xml version="1.0" encoding="utf-8"?>
<ModelType version="1.0" xmlns="http://www.arekusu.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="Model.xsd">
<DefinitionType rootElement="Transport">
    <EntityType alias="Element">
        <FieldsType schema="TestSchema" table="TestTable">
            <FieldType alias="Field1" column="TestColumn"/>
            <FieldType alias="Field2" column="AnotherTestColumn"/>
        </FieldsType>
        <ReferencesType>
            <EntityType alias="RefElement" sourceField="" destinationField="" />
            <EntityType />
        </ReferencesType>
        <LinksType>
            <EntityType alias="LinkedElement" sourceField="" destinationField="" />
            <EntityType />
        </LinksType>
    </EntityType>
</DefinitionType>
</ModelType>
